### ISSUE TITLE
drag-and-drop reorder of taskbar doesn't work

### ISSUE THREAD

**Issue by jonleivent** [LBCrion/sfwbar#104]
The man page says:
```
If the items are not sorted, user can sort them manually via drag-and-drop mechanism.
```
but the drag-and-drop mechanism to reorder the taskbar does not work.  Unless this has to be enabled by adding a specific action to the taskbar?

**Comment by LBCrion** [comment]
Looks like I broke it when implementing modifiers support for actions. Should be fixed now. Thank you for reporting!

**Comment by jonleivent** [comment]
I'll pull and rebuild.  Thanks!

**Comment by jonleivent** [comment]
Still doesn't work.  But, now I get the mouse gripper cursor when trying it.

**Comment by LBCrion** [comment]
What happens after you a grip? Can you drag the grip over another taskbar item? Also, if you release the grip over the adjacent item in the half closer to the item you're dragging, your item won't move, you'll need to release it over the further away half of the destination item.

**Comment by jonleivent** [comment]
The click and drag motion produces the small grip mouse cursor with an arrow while over the task bar, and a slightly larger grip mouse cursor without an arrow when dragged off the task bar.  But, nothing gets dragged with the cursor, no matter how far away it is dragged (when the cursor is the small grip with arrow, hence still on the task bar).

**Comment by LBCrion** [comment]
Can you try to drag this cursor and release it over another taskbar item
(preferably not one next to the original one). The drag cursor is all that
you're dragging here normally.

**Comment by jonleivent** [comment]
That is what I have been doing.  I wasn't expecting the taskbar tab
to get dragged along with the mouse (although that would be cool).

**Comment by jonleivent** [comment]
I didn't have sort set at all.  Now that I have it set to false, the
drag and drop works!  I guess sort defaults to true?  The man page
doesn't say this (but it does have two duplicate entries for the sort
setting).

**Comment by LBCrion** [comment]
I think the sort option is listed 3 times, once for taskbar, once for pager and once for tray. I'll add clarification that this needs to be set to false to enable drag and drop.

**Comment by LBCrion** [comment]
Hi @jonleivent, is there anything left outstanding on this issue or can I close it?

**Comment by jonleivent** [comment]
@LBCrion 
The drag-n-drop on the taskbar has been working perfectly!  Yes, this can be closed.
