### ISSUE TITLE
Feature request: advanced widget interaction

### ISSUE THREAD

**Issue by milochadam** [LBCrion/sfwbar#12]
I would like to create a (sound) widget that reacts to mouse clicks (left/right, maybe middle would be useful too?) and mouse scroll (something like Cinnamon Sound applet).
I would like to change volume on scroll.
Currently the widget looks like this, for the interested:
```
scanner {
  Exec("pamixer --get-volume") {
    Volume= Grab()
  }
}

layout {
  style = "frame"
  css = "* { border: none; box-shadow: none; }"
  label {
    interval = 50
    css = "* { font: 0.3cm Fira Code; font-weight: 700; -GtkWidget-vexpand: true; -GtkWidget-hexpand: true; -GtkWidget-align: 0.5;  }"
    value = Volume
  }
}
```

**Comment by LBCrion** [comment]
Are you just looking to have multiple actions bound to different mouse click/scroll events, all of them executing different commands? That shouldn't be too hard to implement. 
Does the attached widget behave well in terms of CPU utilization? With interval = 50, it executes pamixer 20 times per second.

**Comment by milochadam** [comment]
Ideally I would also want to have an interactive menu with options like running `cinnamon-settings sound` or `pavucontrol` or changing default sink.
As for the low interval I haven't noticed any spikes or high utilisation so far. Maybe setting it to a higher value would be better but I get irritated when I see a visible delay when changing volume.

**Comment by LBCrion** [comment]
This is both doable and fits the goals of sfwbar nicely. It will take some time to implement, but this is now next on my list.

**Comment by LBCrion** [comment]
Actions for different buttons are now in the main git branch. You can specify them as action[n] = "...", the button numbers supported are 1,2,3 for left, middle, right mouse buttons and 4,5,6,7 for up,down, left, right scroll. This works for all widgets except for buttons (these are handled by gtk internally and multiple events for these would be clunky).

**Comment by milochadam** [comment]
Actions work for label widget, actions for buttons stopped working though (nothing happens when I click).
It also messes with styles but maybe I'll find a workaround.
For the following config clicking on the image segfaults. Is image not supported with actions?
```
scanner {
  Exec("pamixer --get-volume") {
    Volume= Grab()
  }
}

layout {
  style = "pager"
  css = "* { border: none; box-shadow: none; }"
  label {
    interval = 50
    value = $Volume
    css = "* { min-width: 2cm; font: 0.3cm Fira Code; font-weight: 700; -GtkWidget-vexpand: true; -GtkWidget-hexpand: true; -GtkWidget-align: 1; }"
  }
  image {
    css = "* { min-width: 1.0cm; min-height: 1.0cm; -GtkWidget-vexpand: true;  }"
    value = '/usr/share/icons/ePapirus-Dark/24x24/actions/speaker.svg'
    action[3] = "pamixer -t"
    action[5] = "pamixer -d 5"
    action[4] = "pamixer -i 5"
  }
}
```
What I'm trying to achieve is to have text value of current volume and speaker image next to it. I want to specify actions for the whole thing, so I don't have to click only label or only image, I would like to specify an action for the whole width of the widget (and height).

**Comment by LBCrion** [comment]
Button widget should work again. Images should work, I fixed a potential bug for this, but not sure if that's what was causing a segfault. Can you please try if the current git version still segfaults?

**Comment by milochadam** [comment]
Button still don't work unfortunately. In the debug log there is:
```
07:27:51,89 widget action 1: Line wrap
```
or
```
07:29:31,62 widget action 1: A list of style attributes to apply to the text of the label
```
and then it segfaults.
Clicking on image with defined actions also segfaults, though not always.

**Comment by LBCrion** [comment]
Ok, I think see what happened. If the widget had a static value, I freed the object which was still needed for actions. Should be fixed in the latest git main.

**Comment by LBCrion** [comment]
Button widgets should support actions on multiple mouse buttons as well now.

**Comment by milochadam** [comment]
It works, thank you!

**Comment by LBCrion** [comment]
User defined menus should also work now. Menus are defined outside of the layout as following:

menu("mymenu") {
  item("item1", Exec "alacritty -e top")
  item("item2", SwayCmd "focus next")
  separator
  submenu("sub") {
    item("item3", Exec "something else")
  }
}

and linked to a widget in the layout, i.e.

layout {
  image {
    value = "icon.svg"
    action[3] = Menu "mymenu"
  }
}

**Comment by milochadam** [comment]
Nice, it works well! Would it be possible to create entries dynamically? It would be useful for changing default input/output

**Comment by LBCrion** [comment]
I was thinking about this, but still trying to figure out a good way to implement this feature. I.e. what would be the source of a new menu. My current thinking is to execute a script and use it's output to populate the menu (somewhat similar to fvwm's PipeRead).

**Comment by LBCrion** [comment]
Dynamic menus should work now. I used the same approach as in fvwm, using user defined functions and piperead. Here's an example:

function("MakeMenu") {
MenuClear "DynamicMenu"
PipeRead "$HOME/bin/makemenu.sh"
Menu "DynamicMenu"
}

layout {
image {
value  = "something.svg"
action[3] = Function "MakeMenu"
}
}

the above assumes that shell script makemenu.sh outputs a valid menu named DynamicMenu, i.e.

#!//bin/sh
echo 'menu("DynamicMenu") { item("Item1", Exec "something") }`
