### ISSUE TITLE
SetLayer not working

### ISSUE THREAD

**Issue by 01micko** [LBCrion/sfwbar#24]
In my setup I have this:

```
function("SfwbarInit") {
  SetLayer "background"
  SetMonitor "DVI-D-1"
}
```

The bar starts on the correct monitor but not on the 'background' layer. See screenshot: (clarification: not that I _want_ 'background' but same thing with 'bottom', which I do want if I run a second instance of the bar)

![sfw-bug](https://user-images.githubusercontent.com/1019119/156906387-4a431e01-0b56-417b-a642-ad956c570d7b.png)

For comparison I drew a simple `gtkdialog` window invoking `gtk-layer-shell` - the second 2 attributes to the `<window>` widget. Firefox or Celluloid can not go into 'fullscreen'. It seems to me that `sfwbar` is always starting on `overlay`.

Running latest `labwc v0.5` branch.

Thanks and if you need any more info I'll provide as time permits.

**Comment by 01micko** [comment]
https://github.com/LBCrion/sfwbar/blob/0528cd21ab5bbbbeea6df5cf088604706022c67c/src/sfwbar.c#L70

Does this line give the trouble?

Another thing, no such issue in `yambar` but it uses no toolkit. I'm wondering if there is a bug in `gtk-layer-shell` preventing firefox, celluloid et-al from going into fullscreen. This has implications for games as well. Of course it could be labwc too, but it's ok with yambar.

**Comment by LBCrion** [comment]
You're right,  I needed to re-initialize the window on changing monitor and
didn't keep track of layer changes.  This should be fixed in the latest got
version.  Can you please check if it fixes the issue?

**Comment by 01micko** [comment]
Yes it does. But I still think there's a bug in `gtk-layer-shell` because if SetLayer="top" or "overlay", firefox or celluloid still can't go fullscreen. So perhaps not your issue now I believe. :-)

**Comment by 01micko** [comment]
This is the config that alerted me to the issue - just a launcher to complement the main bar.

```sh
function("SfwbarInit") {
  SetLayer "bottom"
  SetMonitor "DVI-D-1"
  SetBarSize "200"
}

layout {
  style = frame

  button {
    value = "home"
    action = "defaultfilemanager"
    tooltip = "file manager"
    css = "* { min-height: 36px; min-width: 36px; }"
  }

  button {
    value = "browser"
    action = "defaultbrowser"
    tooltip = "browser"
    css = "* { min-height: 36px; min-width: 36px; }"
  }

  button {
    value = "spreadsheet"
    action = "defaultspreadsheet"
    tooltip = "spread sheet"
    css = "* { min-height: 36px; min-width: 36px; }"
  }

  button {
    value = "document"
    action = "defaultwordprocessor"
    tooltip = "word processor"
    css = "* { min-height: 36px; min-width: 36px; }"
  }

  button {
    value = "paint"
    action = "defaultpaint"
    tooltip = "paint"
    css = "* { min-height: 36px; min-width: 36px; }"
  }

  button {
    value = "edit"
    action = "defaulttexteditor"
    tooltip = "text editor"
    css = "* { min-height: 36px; min-width: 36px; }"
  }
  
  button {
    value = "system-monitor"
    action = "lxtask"
    tooltip = "system monitor"
    css = "* { min-height: 36px; min-width: 36px; }"
  }
}

#CSS
window {
  -GtkWidget-direction: bottom;
	border-radius: 6px;
	background-color: rgba(17, 17, 17, 0.2);
}

button {
  border-width: 0.5px;
  border-radius: 6px;
  margin: 6px;
}
```

And screenshots

![bottom-bar0](https://user-images.githubusercontent.com/1019119/156921564-c441a561-8ced-473a-9b56-d45951231d02.png)

![bottom-bar1](https://user-images.githubusercontent.com/1019119/156921573-b8e52054-2dfc-4acd-a3cd-9c3d5984d2f3.png)


All good now!

**Comment by LBCrion** [comment]
Does placing a bar on a top or overlay layer in other applications prevent
windows from going full screen? (Yambar is a good example,  since it
doesn't use gtk-layer-shell).

**Comment by LBCrion** [comment]
I suspect this behaviour may be caused by the exclusive zone set to true.
It should be possible to add a control for this.

**Comment by LBCrion** [comment]
Can you try replacing:

gtk_layer_auto_exclusive_zone_enable (win);

With:

gtk_layer_shell_set_exclusive_zone(win, 0);

In line 70 in sfwbar.c and see if that gives you the desired behaviour?

**Comment by 01micko** [comment]
> gtk_layer_shell_set_exclusive_zone(win, 0);

gtk_layer_set_exclusive_zone(win, 0);

Still not desired behaviour with firefox, celluloid.

I have `SetLayer "top"`

**Comment by LBCrion** [comment]
Do you get desired behaviour with other bars? With the above change and
layer set to top, I see windows maximise to full screen in sway,  but not
in labwc or wayfire. If you have examples of bars that work for you,  I can
try and see what they do differently.

**Comment by 01micko** [comment]
Latest `yambar`, and I just updated `labwc` to git latest, and things are a bit different. Yambar now supports `layer` in the config, `top` or `bottom`.


#### yambar
With `top` set things are similar to here, whereas before there wasn't setting and things behaved nicely, however, with `bottom` set it behaves as before, fullscreen apps work, but still has exclusive zone for most apps (vivaldi excepted, but I didn't try vivaldi in my old setup, so can't say if it behaved same as firefox, bearing in mind, labwc just had big(ish) merge of `scene graph` branch).

#### sfwbar

There's something interesting going on now that I updated labwc

This screencap, the bar is set to "overlay" however if I run my simple `gtkdialog` app set to overlay it overrides the bar...

![20220307_19h19m06s_grim](https://user-images.githubusercontent.com/1019119/157003085-f93b1af1-34c5-41ba-ac86-6b21046b9a35.png)

.. and then my app set to "top", works as expected
![20220307_19h19m42s_grim](https://user-images.githubusercontent.com/1019119/157003383-ed9ee672-e9b5-4ccc-ad0e-b9c0dea6703d.png)

Same with when I set `sfwbar` to "top", my app overrides when I set "top", and of course not when on "bottom" and so on.

`sfwbar` behaves almost identical to `yambar` when now set to bottom. I don't think there is anything you can do, I can live with it on the bottom layer.

It begs the question; Why does my simple ([gtkdialog](https://github.com/puppylinux-woof-CE/gtkdialog) developed by a few hacks and maintained by a few more) app draw over the bar and apps developed by gnome and mozilla developers don't? Surely they use `gtk-layer-shell` or at least some interpretation of the [wlr-layer-shell-unstable-v1.xml](https://gitlab.freedesktop.org/wlroots/wlr-protocols/-/blob/master/unstable/wlr-layer-shell-unstable-v1.xml) ?

**Comment by Consolatis** [comment]
> But I still think there's a bug in `gtk-layer-shell` because if SetLayer="top" or "overlay", firefox or celluloid still can't go fullscreen. So perhaps not your issue now I believe. :-)

I think this is based on a pretty vague specification for layer-shell [^0]. It doesn't specify where usual fullscreen applications should be rendered, only that usual applications (those that don't use layer-shell) should be rendered between bottom and top layers. Personally, I think it would make sense for labwc to render fullscreen applications between top and overlay layer.

I agree that none of this looks like a bug in sfwfbar.

> It begs the question; Why does my simple ([gtkdialog](https://github.com/puppylinux-woof-CE/gtkdialog) developed by a few hacks and maintained by a few more) app draw over the bar and apps developed by gnome and mozilla developers don't? Surely they use gtk-layer-shell

Most applications are not using the layer-shell protocol, it was designed with desktop components in mind like
- lock screens (overlay layer)
- notifications (top or overlay layer)
- panels (bottom layer + exclusive zone or top layer)
- wallpaper (background)

It is quite possible that current labwc master branch renders some combinations of wayland popups / unmanaged X11 windows / layershell popups / fullscreen in a wrong order. If you detect something like that please open an issue.

[^0]: https://gitlab.freedesktop.org/wlroots/wlr-protocols/-/blob/master/unstable/wlr-layer-shell-unstable-v1.xml#L76

**Comment by LBCrion** [comment]
Indeed, GTK windows are implemented as xdg shell and gtk-layer-shell has to
jump through quite a few hoops to apply layer shell to them.

I added SetLayerShell action to the latest git, but I think any other
changes to the behaviour would need to be implemented on the compositor
side.

Very nice screenshots by the way. They look way better than my default
configs.

**Comment by johanmalm** [comment]
Does sfwbar use OVERLAY layer by default?
https://github.com/LBCrion/sfwbar/blob/a3233b9963f737e961478a724ccf63ae48695db1/src/sfwbar.c#L19

**Comment by johanmalm** [comment]
I'm about to push a labwc fix to that fullscreen views are rendered above the top-layer. 
I will leave the overlay-layer though - otherwise you can't run swaylock from a fullscreen terminal.

**Comment by LBCrion** [comment]
Overlay is the default (this was the default behaviour from early versions
and I don't want to break it), but the layer is easily configurable now,
so if Top is preferred,  I can set it in the default config.

**Comment by johanmalm** [comment]
The layer-shell protocol doesn't actually say where panels should go and there is a lot to be said for avoiding regression, but in my opinion `overlay` seems wrong for a panel.
Anyway - just my 2p's worth. It's a cool panel.

**Comment by LBCrion** [comment]
Actually,  looking at how the two behave under normal conditions,  Top
works as well as overlay. If it means we'll get a better maximise behaviour
on labwc with default settings,  it's worth changing it.  Should be updated
in the current git.
