### ISSUE TITLE
vm parser complains about alignment

### ISSUE THREAD

**Issue by Consolatis** [LBCrion/sfwbar#276]
I am getting a lot of alignment errors when starting sfwbar (compiled with `-Db_sanitize=address,undefined` but not sure if related):

```
test@odroidc4:/home/user/dev/sfwbar$ build/sfwbar
../src/vm/parser.c:157:34: runtime error: store to misaligned address 0xffffe96239a1 for type 'const void *', which requires 8 byte alignment
0xffffe96239a1: note: pointer points here
 ff 00 00  c0 39 62 e9 ff ff 00 00  08 13 77 9d ff ff 00 00  10 3a 62 e9 ff ff 00 00  00 00 00 00 00
              ^ 
../src/vm/parser.c:32:10: runtime error: member access within misaligned address 0xffffe9623981 for type 'struct value_t', which requires 8 byte alignment
0xffffe9623981: note: pointer points here
 00 00 00  00 49 62 e9 ff ff 00 00  00 00 00 00 00 00 00 00  20 00 00 00 00 00 00 00  20 11 81 8d ff
              ^ 
../src/vm/parser.c:32:10: runtime error: member access within misaligned address 0xffffe9623981 for type 'struct value_t', which requires 8 byte alignment
0xffffe9623981: note: pointer points here
 00 00 00  00 00 62 e9 ff ff 00 00  00 00 00 00 00 00 00 00  20 00 00 00 00 00 00 00  20 11 81 8d ff
              ^ 
../src/vm/parser.c:38:34: runtime error: store to misaligned address 0xffff8a843572 for type 'gint', which requires 4 byte alignment
0xffff8a843572: note: pointer points here
 00 28  40 02 3e 62 e9 ff 04 3a  7f a6 8f ff ff 00 00 00  00 62 e9 ff ff 00 00 00  00 00 00 00 00 00
              ^ 
../src/vm/parser.c:131:34: runtime error: store to misaligned address 0xffffe9623e42 for type 'const void *', which requires 8 byte alignment
0xffffe9623e42: note: pointer points here
 00 00  60 3e 62 e9 ff ff 00 00  08 13 77 9d ff ff 00 00  b0 3e 62 e9 ff ff 00 00  80 59 22 96 ff ff
              ^ 
../src/vm/vm.c:149:10: runtime error: load of misaligned address 0xffff8aa8188b for type 'gchar *', which requires 8 byte alignment
0xffff8aa8188b: note: pointer points here
 3a  25 53 00 05 01 92 7f a6  8f ff ff 00 00 be be be  be be be be be be be be  03 00 00 00 00 00 00
              ^ 
05:38:04.69 gtk-layer-shell v0.7.0 may not work on GTK v3.24.38. If you experience crashes, check https://github.com/wmww/gtk-layer-shell/blob/master/compatibility.md
../src/vm/vm.c:201:10: runtime error: load of misaligned address 0xffff8b29ed4b for type 'gchar *', which requires 8 byte alignment
0xffff8b29ed4b: note: pointer points here
 09  00 00 00 04 f2 80 a6 8f  ff ff 00 00 be be be be  be be be be be be be be  b9 96 6e cc 00 00 00
              ^ 
../src/vm/vm.c:214:6: runtime error: load of misaligned address 0xffff8b2a094e for type 'struct value_t', which requires 8 byte alignment
0xffff8b2a094e: note: pointer points here
 11 00 00 00 00 01  63 70 75 5f 63 68 61 72  74 00 02 09 00 00 00 00  01 68 69 64 64 65 6e 00  be be
             ^ 
../src/vm/vm.c:248:15: runtime error: load of misaligned address 0xffff8b2a095b for type 'guint', which requires 4 byte alignment
0xffff8b2a095b: note: pointer points here
 72  74 00 02 09 00 00 00 00  01 68 69 64 64 65 6e 00  be be be be be be be be  be be be be be be be
              ^ 
../src/vm/vm.c:253:17: runtime error: load of misaligned address 0xffff94e73b83 for type 'gint', which requires 4 byte alignment
0xffff94e73b83: note: pointer points here
 00  00 3c 01 16 00 00 00 00  00 62 e9 ff ff 00 00 00  00 00 00 00 00 00 00 00  02 1b 00 00 00 00 00
              ^ 
```
There are also a lot of these ones (25 to be precise) but I don't know if they are related either:
```
(sfwbar:4078811): GLib-CRITICAL **: 05:38:04.869: g_hash_table_lookup: assertion 'hash_table != NULL' failed
```

**Comment by Consolatis** [comment]
> Does this cause any issues with the executable?

None that I recognized so far. I just wondered about the runtime errors on startup.

**Comment by LBCrion** [comment]
Actually, this isn't as innocuous as I thought initially. The code here
relied on an underfined behavior. It should hopefully be fixed now. Can you
please check if you still see any of the messages?

**Comment by Consolatis** [comment]
I am getting a alsa compile error:
<details><summary>alsa error</summary>

```
ninja: Entering directory `/home/user/dev/sfwbar/build'
[53/70] Compiling C object alsactl.so.p/modules_alsactl.c.o
FAILED: alsactl.so.p/modules_alsactl.c.o
cc -Ialsactl.so.p -I. -I.. -I../src -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/uuid -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib/aarch64-linux-gnu/dbus-1.0/include -I/usr/include/at-spi-2.0 -I/usr/include/gtk-layer-shell -I/usr/include/json-c -fdiagnostics-color=always -fsanitize=address,undefined -fno-omit-frame-pointer -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -O0 -g -fPIC -pthread -MD -MQ alsactl.so.p/modules_alsactl.c.o -MF alsactl.so.p/modules_alsactl.c.o.d -o alsactl.so.p/modules_alsactl.c.o -c ../modules/alsactl.c
../modules/alsactl.c:666:4: error: ‘ModuleInterfaceV1’ has no member named ‘finalize’
  666 |   .finalize = alsa_finalize
      |    ^~~~~~~~
../modules/alsactl.c:666:15: error: excess elements in struct initializer [-Werror]
  666 |   .finalize = alsa_finalize
      |               ^~~~~~~~~~~~~
../modules/alsactl.c:666:15: note: (near initialization for ‘sfwbar_interface’)
```

</details>
With 52124460e8f21a3cf6968382a7f00c85a7947706 reverted I can compile but get a UAF by ASAN when starting:

<details><summary> vm/vm.c</summary>

```
test@odroidc4:/home/user/dev/sfwbar$ build/sfwbar
../src/vm/parser.c:32:10: runtime error: member access within misaligned address 0xffffc76f1a91 for type 'struct value_t', which requires 8 byte alignment
0xffffc76f1a91: note: pointer points here
 00 00 00  00 2a 6f c7 ff ff 00 00  00 00 00 00 00 00 00 00  20 00 00 00 00 00 00 00  c0 10 41 a0 ff
              ^ 
../src/vm/parser.c:32:10: runtime error: member access within misaligned address 0xffffc76f1a91 for type 'struct value_t', which requires 8 byte alignment
0xffffc76f1a91: note: pointer points here
 00 00 00  00 00 6f c7 ff ff 00 00  00 00 00 00 00 00 00 00  20 00 00 00 00 00 00 00  c0 10 41 a0 ff
              ^ 
=================================================================
==4116953==ERROR: AddressSanitizer: unknown-crash on address 0xffff9d879791 at pc 0xffffb038c800 bp 0xffffc76f2040 sp 0xffffc76f2058
READ of size 16 at 0xffff9d879791 thread T0
    #0 0xffffb038c7fc in vm_immediate ../src/vm/vm.c:215
    #1 0xffffb038d724 in vm_run ../src/vm/vm.c:245
    #2 0xffffb038f404 in vm_expr_eval ../src/vm/vm.c:327
    #3 0xffffb0383d14 in expr_cache_eval ../src/vm/expr.c:796
    #4 0xffffb03a225c in base_widget_set_style ../src/gui/basewidget.c:524
    #5 0xffffb03f48ac in config_widget_property ../src/config/layout.c:190
    #6 0xffffb03f5db0 in config_widget ../src/config/layout.c:430
    #7 0xffffb03f5d2c in config_widget_child ../src/config/layout.c:409
    #8 0xffffb03f5dc8 in config_widget ../src/config/layout.c:432
    #9 0xffffb03f6298 in config_popup ../src/config/layout.c:469
    #10 0xffffb03fba04 in config_parse_toplevel ../src/config/toplevel.c:343
    #11 0xffffb03f29f8 in config_parse_data ../src/config/init.c:284
    #12 0xffffb03f2e70 in config_parse ../src/config/init.c:340
    #13 0xffffb03f41c4 in config_include ../src/config/layout.c:116
    #14 0xffffb03f5ae0 in config_widget_child ../src/config/layout.c:387
    #15 0xffffb03fb960 in config_parse_toplevel ../src/config/toplevel.c:330
    #16 0xffffb03f29f8 in config_parse_data ../src/config/init.c:284
    #17 0xffffb03f2e70 in config_parse ../src/config/init.c:340
    #18 0xaaaac46f400c in activate ../src/sfwbar.c:113
    #19 0xffffb1107b80 in g_closure_invoke (/lib/aarch64-linux-gnu/libgobject-2.0.so.0+0x17b80)
    #20 0xffffb111d3dc  (/lib/aarch64-linux-gnu/libgobject-2.0.so.0+0x2d3dc)
    #21 0xffffb111e6f4  (/lib/aarch64-linux-gnu/libgobject-2.0.so.0+0x2e6f4)
    #22 0xffffb11240b0 in g_signal_emit_valist (/lib/aarch64-linux-gnu/libgobject-2.0.so.0+0x340b0)
    #23 0xffffb1124170 in g_signal_emit (/lib/aarch64-linux-gnu/libgobject-2.0.so.0+0x34170)
    #24 0xffffaf4fbedc  (/lib/aarch64-linux-gnu/libgio-2.0.so.0+0xfbedc)
    #25 0xffffaf4fc020 in g_application_run (/lib/aarch64-linux-gnu/libgio-2.0.so.0+0xfc020)
    #26 0xaaaac46f46b0 in main ../src/sfwbar.c:154
    #27 0xffffaf662148 in __libc_start_call_main ../sysdeps/aarch64/libc-start.c:58
    #28 0xffffaf66221c in __libc_start_main_impl ../sysdeps/nptl/libc_start_call_main.h:360
    #29 0xaaaac46f39ac in _start (/home/user/dev/sfwbar/build/sfwbar+0x39ac)

0xffff9d8797a0 is located 0 bytes to the right of 16-byte region [0xffff9d879790,0xffff9d8797a0)
allocated by thread T0 here:
    #0 0xffffb069f1c4 in __interceptor_realloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:164
    #1 0xffffb00e5868 in g_realloc (/lib/aarch64-linux-gnu/libglib-2.0.so.0+0x65868)
    #2 0xffffb00a1bfc  (/lib/aarch64-linux-gnu/libglib-2.0.so.0+0x21bfc)
    #3 0xffffb00a2610 in g_array_append_vals (/lib/aarch64-linux-gnu/libglib-2.0.so.0+0x22610)
    #4 0xffffb00a45e4 in g_byte_array_append (/lib/aarch64-linux-gnu/libglib-2.0.so.0+0x245e4)
    #5 0xffffb0385374 in parser_emit_string ../src/vm/parser.c:22
    #6 0xffffb03870cc in parser_value ../src/vm/parser.c:191
    #7 0xffffb03874b8 in parser_ops ../src/vm/parser.c:229
    #8 0xffffb03874f4 in parser_ops ../src/vm/parser.c:231
    #9 0xffffb03874f4 in parser_ops ../src/vm/parser.c:231
    #10 0xffffb03874f4 in parser_ops ../src/vm/parser.c:231
    #11 0xffffb03874f4 in parser_ops ../src/vm/parser.c:231
    #12 0xffffb0387900 in parser_expr_parse ../src/vm/parser.c:258
    #13 0xffffb0388518 in parser_expr_compile ../src/vm/parser.c:301
    #14 0xffffb0384274 in expr_cache_set ../src/vm/expr.c:837
    #15 0xffffb03a2110 in base_widget_set_style ../src/gui/basewidget.c:521
    #16 0xffffb03f48ac in config_widget_property ../src/config/layout.c:190
    #17 0xffffb03f5db0 in config_widget ../src/config/layout.c:430
    #18 0xffffb03f5d2c in config_widget_child ../src/config/layout.c:409
    #19 0xffffb03f5dc8 in config_widget ../src/config/layout.c:432
    #20 0xffffb03f6298 in config_popup ../src/config/layout.c:469
    #21 0xffffb03fba04 in config_parse_toplevel ../src/config/toplevel.c:343
    #22 0xffffb03f29f8 in config_parse_data ../src/config/init.c:284
    #23 0xffffb03f2e70 in config_parse ../src/config/init.c:340
    #24 0xffffb03f41c4 in config_include ../src/config/layout.c:116
    #25 0xffffb03f5ae0 in config_widget_child ../src/config/layout.c:387
    #26 0xffffb03fb960 in config_parse_toplevel ../src/config/toplevel.c:330
    #27 0xffffb03f29f8 in config_parse_data ../src/config/init.c:284
    #28 0xffffb03f2e70 in config_parse ../src/config/init.c:340
    #29 0xaaaac46f400c in activate ../src/sfwbar.c:113

SUMMARY: AddressSanitizer: unknown-crash ../src/vm/vm.c:215 in vm_immediate
Shadow bytes around the buggy address:
  0x200ff3b0f2a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x200ff3b0f2b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x200ff3b0f2c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x200ff3b0f2d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x200ff3b0f2e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa 00 00
=>0x200ff3b0f2f0: fa fa[00]00 fa fa fd fd fa fa 00 04 fa fa fd fd
  0x200ff3b0f300: fa fa fd fa fa fa fd fd fa fa fd fd fa fa fd fd
  0x200ff3b0f310: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
  0x200ff3b0f320: fa fa 00 00 fa fa fd fd fa fa fa fa fa fa fa fa
  0x200ff3b0f330: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x200ff3b0f340: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==4116953==ABORTING
```
</details>

**Comment by LBCrion** [comment]
Yes,  I missed a file in the commit.  Will update it once kids go to sleep
;)

**Comment by LBCrion** [comment]
Should be OK now

**Comment by Consolatis** [comment]
Yep, alsa issue is fixed. Still getting the same ASAN "unknown-crash" in `src/vm/vm.c:215` as before though. Same for the two misaligned runtime errors in `src/vm/parser.c:32`.

**Comment by Consolatis** [comment]
Without ASAN I am getting a double free in `src/vm/vm.c:88` instead.

**Comment by LBCrion** [comment]
I think the remaining unaligned pointer use should be fixed as well as the
unknown-crash. Double free in vm.c:88 looks odd. I'll need to trace this
one down.

**Comment by LBCrion** [comment]
Thank you, I think the full backtrace pointed me in the right direction -
there was a possibility of the variable value query returning an
uninitialized value. Can you please check to see if you still see a bug
when you get a chance?

**Comment by Consolatis** [comment]
I think you found the culprit, no more double free without ASAN.
Also no more misaligned address errors with ASAN. Nice job!

Still getting the `hash table != NULL` asserts but I assume those are completely unrelated and I also don't know how to debug them without recompiling my GTK 3 stack.

**Comment by LBCrion** [comment]
I think all hash table use cases should have proper NULL guards now. Do you still see any ``hash table != NULL`` assertions?

**Comment by Consolatis** [comment]
Latest main branch compiles cleanly, no more GTK asserts when running. Everything looks good here :)
