### ISSUE TITLE
taskbar broken after `eb263f4befc5bcaa3167fd69ee248f8e67b142c5`

### ISSUE THREAD

**Issue by Flrian** [LBCrion/sfwbar#286]
After commit eb263f4befc5bcaa3167fd69ee248f8e67b142c5 the taskbar module seems to be broken. Only applications that are started before sfwbar show up in the taskbar and I'm not able to switch between them via mouse click.

**Comment by LBCrion** [comment]
Can you try the latest git version and see if you're still getting this
issue? I haven't seen it locally, but the code is changing is quickly right
now that I could have easily broken things and fixed them without noticing.

**Comment by LBCrion** [comment]
Can I check, are you using alsa or pulse for your audio system?

And keep them coming! With a big rewrite, it can be hard to keep track of
what needs fixing, so bug reports are very valuable.

**Comment by LBCrion** [comment]
Also, parser errors in winops should be fixed now.

**Comment by LBCrion** [comment]
I missed a file from the last commit.  Should be fixed now.

**Comment by sfs-pra** [comment]
sfwbar-git-r1693.86654c1 :
trigger: 'volume-conf' -  problem remains

**Comment by LBCrion** [comment]
Does this message appear eve when you're running without debug enabled?
I.e. without '-d' option? The only "trigger: 'name'" message I see in the
source code should be behind the debug flag and should only appear when the
debug mode is enabled.

Also, does the message print continuously, preventing the bar from
operating for you as well?

**Comment by sfs-pra** [comment]
sfwbar-git-r1697.de2d42b 
"trigger: 'name'"  with '-d' option
Added "trigger: 'wifi_scan'" and swbar won't start.

**Comment by LBCrion** [comment]
Also, does trigger: volume-conf continue printing indefinitely, or is there
just a burst of these messages before sfwbar stops responding?

**Comment by sfs-pra** [comment]
sfwbar-git-r1705.818813f - problem solved
