### ISSUE TITLE
filter does not work on other wlroots based WM

### ISSUE THREAD

**Issue by boris3812** [LBCrion/sfwbar#66]
commands to start sfwbar is for 2 outputs : 
sfwbar -f /home/user/.config/sfwbar/sfwbar.config -m HDMI-A-1
sfwbar -f /home/user/.config/sfwbar/sfwbar.config -m DP-1

where configuration file is the example t2.config
https://github.com/LBCrion/sfwbar/blob/main/config/t2.config

with adding propriety filter like is described in man
https://github.com/LBCrion/sfwbar/blob/main/doc/sfwbar.rst
and only 1 modified propriety
....
  taskbar {
    rows = 1
    css = "* { -GtkWidget-hexpand: true; }" # stretch horizontally
    icons = true
    labels = true
    **filter = output**
    action[3] = Menu "winops"
  }
........

But I also have today problem that taskbar shows all tasks, but not only by list for windows what are openned on current  output.
May be it works on sway, but it's still not working on Wayfire and labwc or I just could not find information what I need to change in the config file. At the moment I use Wayfire as WM **on Archlinux**.

yes , I know that the propriety _filter_output = true_ is dpricated in version 1.0 , so I use **filter = output** as you see.
yes , I tried to comment **function("SfwbarInit")**  or to change there propriety **SetMonitor "DP-1"** or **SetMonitor " HDMI-A-1"** , by using 2 configuration files per output - but no result.

Is this a bug that you need to fix it ? or give me please information what I need to modify in config files to get taskbar with tasks from only current output , so at last , we'll have some kind of tint2 for wayland , without X libraries :) .

**Comment by LBCrion** [comment]
This is an oversight on my part. Workspace filtering isn't currently possible on wlr-foreign-toplevel based compositors, so I haven't implemented filtering at all. Output filtering IS possible and should be implemented. I just pushed support for output tracking to the main git branch. 
Can you try it please and see if output filtering works now?

**Comment by boris3812** [comment]
so I tried. I removed AUR package and installed via git clone and meson build like in README.md is described - but it still not working

**Comment by boris3812** [comment]
Interisting... if i launch just sfwbar command - it is reading my file config. but when i use -f flag , it shows:

 sfwbar -f /home/admin/.config/sfwbar/sfwbar.config -m HDMI-A-1

** (sfwbar:17519): ERROR **: 13:45:48.361: Error: can't read config file /home/admin/.config/sfwbar/sfwbar.config

[1]    17519 trace trap  sfwbar -f /home/admin/.config/sfwbar/sfwbar.config -m HDMI-A-1

**Comment by LBCrion** [comment]
> so I tried. I removed AUR package and installed via git clone and meson build like in README.md is described - but it still not working

I rushed a bit last night. Should know better than to commit code late at night. I pushed the updated fix into git. Could you try again when you have a moment please?

**Comment by LBCrion** [comment]
> **sfwbar -f /home/admin/.config/sfwbar/sfwbar.config**
> 
> ** (sfwbar:17857): ERROR **: 13:47:57.352: Error: can't read config file /home/admin/.config/sfwbar/sfwbar.config

This is a bug, introduced in module loader implementation (added after the last release). It should be fixed in the latest git version as well.

**Comment by boris3812** [comment]
yep, that's it !) now output filtering is working fine )

**Comment by LBCrion** [comment]
Great. Thank you for reporting these bugs!

**Comment by LBCrion** [comment]
Fixed in #74
